INSERT INTO WAREHOUSE.INCOMINGDOCUMENT (ID, AMOUNT, AMOUNTTOBEPAID, DELIVERYDATE, PRICE, PRODUCT, SHIPPER, WAREHOUSE) 
	VALUES (5, 40, 400.0, '2013-06-01', 10.0, 'Fanta', 'Delivery Inc.', 'Warehouse5');
INSERT INTO WAREHOUSE.INCOMINGDOCUMENT (ID, AMOUNT, AMOUNTTOBEPAID, DELIVERYDATE, PRICE, PRODUCT, SHIPPER, WAREHOUSE) 
	VALUES (6, 50, 500.0, '2013-06-01', 10.0, 'Coca-Cola', 'Delivery Inc.', 'Warehouse5');
INSERT INTO WAREHOUSE.INCOMINGDOCUMENT (ID, AMOUNT, AMOUNTTOBEPAID, DELIVERYDATE, PRICE, PRODUCT, SHIPPER, WAREHOUSE) 
	VALUES (7, 60, 600.0, '2013-06-01', 10.0, 'Sprite', 'Delivery Inc.', 'Warehouse4');
INSERT INTO WAREHOUSE.INCOMINGDOCUMENT (ID, AMOUNT, AMOUNTTOBEPAID, DELIVERYDATE, PRICE, PRODUCT, SHIPPER, WAREHOUSE) 
	VALUES (8, 50, 500.0, '2013-06-01', 10.0, 'Shweaps', 'Delivery Inc.', 'Warehouse4');
