
INSERT INTO WAREHOUSE.EXPENSEDOCUMENT (ID, AMOUNT, CUSTOMER, DELIVERYDATE, NOTIONALAMOUNT, NOTIONALPRICE, PRODUCT, WAREHOUSE) 
	VALUES (51, 20, 'Ivanov', '2013-06-01', 5670.0, 13.0, 'Fanta', 'Warehouse1');
INSERT INTO WAREHOUSE.EXPENSEDOCUMENT (ID, AMOUNT, CUSTOMER, DELIVERYDATE, NOTIONALAMOUNT, NOTIONALPRICE, PRODUCT, WAREHOUSE) 
	VALUES (52, 40, 'Sergeev', '2013-06-07', 567.0, 12.0, 'Coca-Cola', 'Warehouse3');
INSERT INTO WAREHOUSE.EXPENSEDOCUMENT (ID, AMOUNT, CUSTOMER, DELIVERYDATE, NOTIONALAMOUNT, NOTIONALPRICE, PRODUCT, WAREHOUSE) 
	VALUES (53, 40, 'Snegirev', '2013-06-02', 879.0, 31.0, 'Sprite', 'Warehouse1');
INSERT INTO WAREHOUSE.EXPENSEDOCUMENT (ID, AMOUNT, CUSTOMER, DELIVERYDATE, NOTIONALAMOUNT, NOTIONALPRICE, PRODUCT, WAREHOUSE) 
	VALUES (54, 46, 'Gusarov', '2013-06-03', 345.65, 12.0, 'Fanta', 'Warehouse2');
INSERT INTO WAREHOUSE.EXPENSEDOCUMENT (ID, AMOUNT, CUSTOMER, DELIVERYDATE, NOTIONALAMOUNT, NOTIONALPRICE, PRODUCT, WAREHOUSE) 
	VALUES (55, 76, 'Medvedev', '2013-06-05', 766.0, 34.0, 'Shweaps', 'Warehouse3');
INSERT INTO WAREHOUSE.EXPENSEDOCUMENT (ID, AMOUNT, CUSTOMER, DELIVERYDATE, NOTIONALAMOUNT, NOTIONALPRICE, PRODUCT, WAREHOUSE) 
	VALUES (56, 89, 'Sergeev', '2013-06-04', 544.0, 56.0, 'Pepsi', 'Warehouse4');
INSERT INTO WAREHOUSE.EXPENSEDOCUMENT (ID, AMOUNT, CUSTOMER, DELIVERYDATE, NOTIONALAMOUNT, NOTIONALPRICE, PRODUCT, WAREHOUSE) 
	VALUES (57, 14, 'Ivanov', '2013-06-06', 2334.0, 87.0, 'Coca-Cola', 'Warehouse4');
INSERT INTO WAREHOUSE.EXPENSEDOCUMENT (ID, AMOUNT, CUSTOMER, DELIVERYDATE, NOTIONALAMOUNT, NOTIONALPRICE, PRODUCT, WAREHOUSE) 
	VALUES (58, 356, 'Gusarov', '2013-06-02', 5667.0, 98.0, 'Sprite', 'Warehouse3');
INSERT INTO WAREHOUSE.EXPENSEDOCUMENT (ID, AMOUNT, CUSTOMER, DELIVERYDATE, NOTIONALAMOUNT, NOTIONALPRICE, PRODUCT, WAREHOUSE) 
	VALUES (59, 12, 'Medvedev', '2013-06-01', 123.0, 12.0, 'Pepsi', 'Warehouse2');
INSERT INTO WAREHOUSE.EXPENSEDOCUMENT (ID, AMOUNT, CUSTOMER, DELIVERYDATE, NOTIONALAMOUNT, NOTIONALPRICE, PRODUCT, WAREHOUSE) 
	VALUES (60, 56, 'Snegirev', '2013-06-01', 5678.0, 34.0, 'Fanta', 'Warehouse1');