INSERT INTO WEBSHOP.CATEGORY (ID,  AMOUNT, AVAILABLE,NAMEPRODUCTS,URLFORCONTROLLER) 
	VALUES (1, 23,1,'Ноутбуки','notebook.htm');
INSERT INTO WEBSHOP.CATEGORY (ID,  AMOUNT, AVAILABLE,NAMEPRODUCTS,URLFORCONTROLLER) 
	VALUES (2,45,1, 'Камеры','camera.htm');
INSERT INTO WEBSHOP.CATEGORY (ID,  AMOUNT, AVAILABLE,NAMEPRODUCTS,URLFORCONTROLLER)
	VALUES (3,6,1, 'Книги','book.htm');
INSERT INTO WEBSHOP.CATEGORY (ID,  AMOUNT, AVAILABLE,NAMEPRODUCTS,URLFORCONTROLLER) 
	VALUES (4,0,0, 'Кабель','cable.htm');

